-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.teams (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name text NOT NULL,
  code text NOT NULL UNIQUE,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'archived'::text, 'deleted'::text])),
  archived_by uuid,
  archived_at timestamp with time zone,
  CONSTRAINT teams_pkey PRIMARY KEY (id),
  CONSTRAINT teams_archived_by_fkey FOREIGN KEY (archived_by) REFERENCES public.users(id)
);
CREATE TABLE public.users (
  id uuid NOT NULL,
  email text NOT NULL UNIQUE,
  name text,
  role text NOT NULL DEFAULT 'player'::text CHECK (role = ANY (ARRAY['coach'::text, 'player'::text])),
  team_id uuid,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  activation_key text,
  activated_at timestamp with time zone,
  CONSTRAINT users_pkey PRIMARY KEY (id),
  CONSTRAINT users_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id)
);
CREATE TABLE public.team_members (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  team_id uuid NOT NULL,
  user_id uuid NOT NULL,
  role text NOT NULL CHECK (role = ANY (ARRAY['coach'::text, 'player'::text])),
  joined_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT team_members_pkey PRIMARY KEY (id),
  CONSTRAINT team_members_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id),
  CONSTRAINT team_members_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.matches (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  player_name text,
  playsight_link text,
  video_url text,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'importing'::text, 'generating_frames'::text, 'player_selection'::text, 'court_setup'::text, 'processing'::text, 'completed'::text, 'failed'::text])),
  processed_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  match_date date,
  opponent text,
  notes text,
  s3_temp_key text,
  video_filename text,
  frame_count integer,
  court_setup_status text DEFAULT 'pending'::text CHECK (court_setup_status = ANY (ARRAY['pending'::text, 'ready'::text, 'confirmed'::text])),
  debug_video_status text CHECK (debug_video_status = ANY (ARRAY['generating'::text, 'ready'::text])),
  debug_video_path text,
  poi_start_side text CHECK (poi_start_side = ANY (ARRAY['near'::text, 'far'::text])),
  stats jsonb,
  analysis_shots jsonb,
  analyzed_at timestamp with time zone,
  analysis_error text,
  CONSTRAINT matches_pkey PRIMARY KEY (id),
  CONSTRAINT matches_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.match_data (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  match_id uuid NOT NULL,
  json_data jsonb NOT NULL,
  stats_summary jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT match_data_pkey PRIMARY KEY (id),
  CONSTRAINT match_data_match_id_fkey FOREIGN KEY (match_id) REFERENCES public.matches(id)
);
CREATE TABLE public.shots (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  match_id uuid NOT NULL,
  shot_type text,
  start_pos jsonb,
  end_pos jsonb,
  timestamp integer NOT NULL,
  video_timestamp real,
  result text NOT NULL CHECK (result = ANY (ARRAY['winner'::text, 'error'::text, 'in_play'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  speed_kmh real,
  player text,
  frame integer,
  is_winner boolean DEFAULT false,
  is_error boolean DEFAULT false,
  point_idx integer,
  CONSTRAINT shots_pkey PRIMARY KEY (id),
  CONSTRAINT shots_match_id_fkey FOREIGN KEY (match_id) REFERENCES public.matches(id)
);
CREATE TABLE public.player_identifications (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  match_id uuid NOT NULL,
  frame_data jsonb NOT NULL,
  selected_player_coords jsonb NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT player_identifications_pkey PRIMARY KEY (id),
  CONSTRAINT player_identifications_match_id_fkey FOREIGN KEY (match_id) REFERENCES public.matches(id)
);
CREATE TABLE public.court_configs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  match_id uuid NOT NULL UNIQUE,
  kp0_x real,
  kp0_y real,
  kp1_x real,
  kp1_y real,
  kp2_x real,
  kp2_y real,
  kp3_x real,
  kp3_y real,
  kp4_x real,
  kp4_y real,
  kp5_x real,
  kp5_y real,
  kp6_x real,
  kp6_y real,
  kp7_x real,
  kp7_y real,
  kp8_x real,
  kp8_y real,
  kp9_x real,
  kp9_y real,
  kp10_x real,
  kp10_y real,
  kp11_x real,
  kp11_y real,
  kp12_x real,
  kp12_y real,
  kp13_x real,
  kp13_y real,
  ai_suggested boolean DEFAULT true,
  confirmed_at timestamp with time zone,
  confirmed_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT court_configs_pkey PRIMARY KEY (id),
  CONSTRAINT court_configs_match_id_fkey FOREIGN KEY (match_id) REFERENCES public.matches(id),
  CONSTRAINT court_configs_confirmed_by_fkey FOREIGN KEY (confirmed_by) REFERENCES public.users(id)
);
CREATE TABLE public.points (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  match_id uuid NOT NULL,
  point_idx integer NOT NULL,
  start_frame integer,
  end_frame integer,
  start_timestamp_s real,
  end_timestamp_s real,
  serve_player text CHECK (serve_player = ANY (ARRAY['near'::text, 'far'::text])),
  rally_length integer DEFAULT 0,
  manual_outcome text CHECK (manual_outcome = ANY (ARRAY['winner'::text, 'forced_error'::text, 'unforced_error'::text, 'ace'::text, 'double_fault'::text])),
  reviewed_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT points_pkey PRIMARY KEY (id),
  CONSTRAINT points_match_id_fkey FOREIGN KEY (match_id) REFERENCES public.matches(id)
);